# set Lib Path
# R_LIBS is set by the pipeline to point at the conda environment's R library directory
lib_path <- Sys.getenv('R_LIBS', unset = NA)
if (is.na(lib_path) || lib_path == "") {
  # fallback to default
  .libPaths()[1]
} else {
  .libPaths(lib_path)
}

# load packages
# suppressMessages prevents package startup banners from cluttering pipeline logs
suppressMessages(library(glue)) ; g=glue ; len=length  # convenience aliases used throughout
suppressMessages(library(dplyr))
suppressMessages(library(purrr))
suppressMessages(library(rlist))
suppressMessages(library(rhdf5))
suppressMessages(library(Matrix))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(ggrastr))
suppressMessages(library(cowplot))
suppressMessages(library(viridis))
suppressMessages(library(magrittr))
suppressMessages(library(jsonlite))
suppressMessages(library(gridExtra))
options(warn = -1)
options(future.globals.maxSize = Inf)

# R_FUNC points to the functions/ directory; source the helper file that defines f(), fuzzy_matching(), etc.
r_func_path <- Sys.getenv('R_FUNC', unset = NA)
if (is.na(r_func_path) || r_func_path == "") {
  # inlined rather than using trouble(): this check runs before any helper file is sourced
  stop(paste0("R_FUNC environment variable is not set, so the helper functions cannot be located.",
              "\nTroubleshooting:",
              "\n \u2022 R_FUNC is exported by the pipeline's spatial-analysis stage; run this script through",
              " `./slidr --bcl <BCL_ID> --spatial-analysis` rather than by hand",
              "\n \u2022 To run it by hand, set it to the scripts' functions/ directory, e.g.",
              " R_FUNC=workflow/scripts/spatial_analysis/functions"), call. = FALSE)
}
source(paste0(r_func_path, '/load_matrix_func.R'))


# parse arguments
# out_path is optional and defaults to the working directory when omitted
# percent_umi_filter is optional and defaults to 1 (top 1% of beads by UMI count) when omitted
args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 2) {
  sb_path <- args[[1]]
  cb_path <- args[[2]]
  out_path <- "."
  percent_umi_filter <- 1
} else if (length(args) == 3) {
  sb_path <- args[[1]]
  cb_path <- args[[2]]
  out_path <- args[[3]]
  percent_umi_filter <- 1
} else if (length(args) == 4) {
  sb_path <- args[[1]]
  cb_path <- args[[2]]
  out_path <- args[[3]]
  percent_umi_filter <- as.numeric(args[[4]])
} else {
  stop(trouble(
    "Usage: Rscript load_matrix.R SBcounts_path cb_whitelist_path [output_path] [percent_umi_filter]",
    "This script is normally invoked by the pipeline's spatial-analysis stage, not by hand",
    "Run it through the pipeline with `./slidr --bcl <BCL_ID> --spatial-analysis`",
    paste("Got", length(args), "argument(s):", paste(args, collapse = " "))
  ), call. = FALSE)
}
if (is.na(percent_umi_filter) || percent_umi_filter < 0 || percent_umi_filter > 100) {
  stop(trouble(
    g("percent_umi_filter must be a number between 0 and 100, got: {percent_umi_filter}"),
    "This comes from `workflow.top_n_percent_umi_filter` in the config file -- set it to a number in that range (e.g. 1), unquoted",
    "Remove the field entirely to accept the default of 1"
  ), call. = FALSE)
}
if (!dir.exists(out_path)) { dir.create(out_path, recursive = T) }

# prepend lib_path to PATH so that h5ls (from the HDF5 system package) is discoverable at runtime
Sys.setenv(PATH = paste(lib_path, Sys.getenv("PATH"), sep = .Platform$path.sep))
# verify that the SBcounts HDF5 file has exactly the four expected datasets before loading anything
# shQuote the path arg: system2() passes args through /bin/sh -c unquoted, and sb_path derives
# from metadata (a shared, editable sheet); this h5ls call runs before any file.exists gate
sb_datasets <- tryCatch(
  system2("h5ls", args = shQuote(paste0(sb_path, "/matrix")), stdout = TRUE) %>%
    strsplit(split = "\\s+") %>% map_chr(pluck(1)),
  error = function(e) character(0)
)
if (!isTRUE(all.equal(sb_datasets, c("cb_index", "reads", "sb_index", "umi")))) {
  stop(trouble(
    paste0("the spatial barcode counts file ", sb_path,
           " does not contain the expected matrix datasets (found: ",
           if (length(sb_datasets)) paste(sb_datasets, collapse = ", ") else "nothing", ")"),
    "Expected exactly cb_index, reads, sb_index and umi under the /matrix group",
    "This file is written by spatial_count.jl; an empty or partial result means that stage did not finish",
    "Re-run the spatial-barcode counting stage with --spatial-count --force",
    "`h5ls` must also be on PATH -- it comes from the HDF5 system package in the `r_env` conda environment"
  ), call. = FALSE)
}


# load the CB whitelist — one called-cell barcode per line, written by run_positioning.R from obj$cb
cb_whitelist = readLines(cb_path)
# The whitelist is generated by run_positioning.R from the count matrix's barcodes, so a failure
# here means that matrix is not what this stage expects -- not that the user mistyped something.
CB_WHITELIST_HINTS <- c(
  paste0("The whitelist is generated from the count matrix by the previous step and written to ", cb_path),
  "Check the count (or cellbender) matrix for this sample is a standard 10x gene-expression matrix",
  "Re-run the spatial analysis from scratch with --spatial-analysis --force"
)
if (!is.character(cb_whitelist) || length(cb_whitelist) == 0) {
  stop(trouble(paste0("the cell barcode whitelist at ", cb_path, " is empty or unreadable"),
               c("An empty whitelist means the count matrix contained no called cells",
                 CB_WHITELIST_HINTS)), call. = FALSE)
}
if (any(duplicated(cb_whitelist))) {
  stop(trouble(paste0(sum(duplicated(cb_whitelist)), " duplicate cell barcode(s) in the whitelist at ", cb_path),
               c("Each called cell must appear once, or its spatial reads cannot be attributed to a single cell",
                 CB_WHITELIST_HINTS)), call. = FALSE)
}
if (len(unique(nchar(cb_whitelist))) != 1) {  # all barcodes must be the same length
  stop(trouble(paste0("the cell barcodes in the whitelist have mixed lengths: ",
                      paste(sort(unique(nchar(cb_whitelist))), collapse = ", ")),
               c("All cell barcodes must be the same length for the fixed-width matching used below",
                 CB_WHITELIST_HINTS)), call. = FALSE)
}
if (!all(map_lgl(strsplit(cb_whitelist, ""), ~all(. %in% c("A","C","G","T"))))) {  # no N or non-ACGT bases
  stop(trouble("some cell barcodes in the whitelist contain bases other than A, C, G or T",
               c("Barcodes containing N (or any other character) cannot be matched against the spatial reads",
                 paste0("Offending barcodes include: ",
                        paste(head(cb_whitelist[!map_lgl(strsplit(cb_whitelist, ""), ~all(. %in% c("A","C","G","T")))], 5),
                              collapse = ", ")),
                 CB_WHITELIST_HINTS)), call. = FALSE)
}
log_ts(g("loading the spatial matrix for {len(cb_whitelist)} called cells"))

# load the SB count matrix from the HDF5 file written by spatial_count.jl
# cb_index and sb_index are 1-based integer indices into the cb_list and sb_list stored in lists/
# umi_2bit is a 2-bit encoded UMI used for chimera detection; reads is the raw read count
df = data.frame(cb_index=read_data_from_h5("matrix/cb_index"),
                umi_2bit=read_data_from_h5("matrix/umi"),
                sb_index=read_data_from_h5("matrix/sb_index"),
                reads=read_data_from_h5("matrix/reads"))
log_detail(g("{sum(df$reads)} spatial barcode reads"))

# load metadata written by spatial_count.jl describing the run and filtering statistics
# SB_filtering will accumulate read counts removed at each processing step (waterfall accounting)
metadata = list(SB_info = list(R1s=read_data_from_h5("metadata/R1s"),
                               R2s=read_data_from_h5("metadata/R2s"),
                               UMI_downsampling=read_data_from_h5("metadata/downsampling"),
                               switch_R1R2=read_data_from_h5("metadata/switch") %>% as.logical),
                UP_matching = setNames(read_data_from_h5_64("metadata/UP_matching/count"), read_data_from_h5("metadata/UP_matching/type")),
                SB_matching = setNames(read_data_from_h5_64("metadata/SB_matching/count"), read_data_from_h5("metadata/SB_matching/type")),
                SB_fuzzy_position = setNames(read_data_from_h5_64("metadata/SB_matching/position_count"), read_data_from_h5_64("metadata/SB_matching/position")),
                bead_info = list(num_lowQ=read_data_from_h5_64("metadata/num_lowQbeads"))
)

# reads removed before reaching this script: invalid UMIs (N or homopolymer), no UP site, no SB match
# num_reads is read via read_data_from_h5_64() because rhdf5 silently converts 64-bit HDF5 ints that
# exceed R's 32-bit integer range (>2.1B, common on large runs) to NA instead of erroring
metadata$SB_filtering = c(reads_total=read_data_from_h5_64("metadata/num_reads"),
                          reads_noumi=sum(metadata$UP_matching[c("umi_N","umi_homopolymer")]),
                          reads_noup=sum(metadata$UP_matching[c("none","GG")]),
                          # spatial_count.jl's SB matching has 6 categories; reads rejected at the
                          # SB-matching stage are the three non-placed ones: none, HD1ambig, and
                          # SB2delambig (the second-half-deletion ambiguous class added alongside
                          # SB2del). Omitting SB2delambig here undercounts reads_nosb and breaks the
                          # read-conservation stopifnot below by exactly p["SB2delambig"] reads.
                          reads_nosb=sum(metadata$SB_matching[c("none","HD1ambig","SB2delambig")]))



# fuzzy-match cb_index values from the Julia cb_list into whitelist positions
# cb_list (from HDF5) contains all barcodes seen in the data; cb_whitelist contains only called cells
# after matching: positive cb_index = whitelist position, negative = unmatched (negated original index)
log_ts("matching cell barcodes (fuzzy)")
df %<>% fuzzy_matching(read_data_from_h5("lists/cb_list"), cb_whitelist)
invisible(gc())

# a chimera is a read where the same (CB, UMI) maps to more than one spatial barcode location
# chimeras arise from index hopping or ligation artifacts and are removed before UMI counting
log_ts("removing chimeric reads")
df %<>% remove_chimeras
invisible(gc())

# plot barcode rank plots before whitelist filtering so unfiltered data is visible
log_ts("plotting barcode ranks")
suppressMessages(suppressWarnings(plot_rankplots(df, read_data_from_h5, out_path)))
invisible(gc())

# load puck bead coordinates from HDF5; load_puckdf scales to microns and filters degenerate beads
log_ts("loading the puck")
puckdf <- load_puckdf(read_data_from_h5)

log_ts("plotting beads")
suppressMessages(suppressWarnings(plot_beadplot(df, puckdf, out_path)))

# drop reads whose spatial barcode index was not retained in the quality-filtered puck
# puckdf only contains beads that passed the duplicate, N-content, and degeneracy filters
log_ts("filtering low-quality spatial barcodes")
m = df$sb_index %in% puckdf$sb_index
metadata$SB_filtering %<>% c(reads_lowQsb=sum(df$reads[!m]))
df = df[m,]

# drop reads with a negative cb_index — these are barcodes that didn't match any called cell
log_ts("dropping reads from uncalled cells")
metadata$SB_filtering %<>% c(reads_uncalled=sum(df$reads[df$cb_index < 0]))
df %<>% filter(cb_index > 0)

# count UMIs by collapsing reads sharing the same (CB, SB) pair
# the conservation check verifies that all removed reads account for exactly half of total_reads×2
# (the doubling is because reads_total is added twice when appending reads_final to the named vector)
log_ts("counting UMIs")
if (sum(metadata$SB_filtering)+sum(df$reads) != 2 * metadata$SB_filtering["reads_total"]) {
  log_detail("SB_filtering breakdown (reads accounted for at each step):")
  print(metadata$SB_filtering)
  log_detail(g("sum(SB_filtering) = {sum(metadata$SB_filtering)}"))
  log_detail(g("sum(df$reads) (reads remaining) = {sum(df$reads)}"))
  message(g("sum(SB_filtering) + sum(df$reads) = {sum(metadata$SB_filtering)+sum(df$reads)}"))
  message(g("2 * reads_total = {2 * metadata$SB_filtering[['reads_total']]}"))
  message(g("imbalance = {sum(metadata$SB_filtering)+sum(df$reads) - 2 * metadata$SB_filtering[['reads_total']]}"))
}
if (sum(metadata$SB_filtering)+sum(df$reads) != 2 * metadata$SB_filtering["reads_total"]) {
  stop(trouble(
    "the spatial read accounting does not balance (see the breakdown printed above)",
    "Every read must be accounted for by exactly one filtering category; this inconsistency is a bug in the pipeline's own bookkeeping, not a problem with your data",
    paste0("If `workflow.spatial_downsampling` is set, the downsampled ", basename(sb_path),
           " may have been written by an older version -- delete it and re-run with --spatial-count --force"),
    "Otherwise please report it at https://github.com/kabanovskyd/slidr/issues, quoting the breakdown above"
  ), call. = FALSE)
}
metadata$SB_filtering %<>% c(reads_final=sum(df$reads))
df %<>% count_umis
metadata$SB_filtering %<>% c(UMIs_final=sum(df$umi))
invisible(gc())

# filter out the top N% of beads by total UMI count -- these are typically bead aggregates or
# free-floating bead contamination whose abnormally strong signal would dominate spatial placement
message(g("Filtering top {percent_umi_filter}% of beads by UMI count"))
bead_umi = df %>% group_by(sb_index) %>% summarize(umi=sum(umi), .groups="drop")
if (nrow(bead_umi) == 0) {
  message("WARNING: no reads remained after UMI counting; skipping bead UMI filtering (sample has zero usable spatial data at this step)")
  umi_cutoff = NA_real_
  high_umi_sb = bead_umi$sb_index  # empty, but keeps the type consistent with the non-empty branch
} else {
  umi_cutoff = quantile(bead_umi$umi, 1 - percent_umi_filter / 100, names=F)
  high_umi_sb = bead_umi$sb_index[bead_umi$umi > umi_cutoff]
}
metadata$bead_info$num_highUMI = len(high_umi_sb)
metadata$bead_info$UMI_cutoff = umi_cutoff
metadata$bead_info$percent_umi_filter = percent_umi_filter
metadata$SB_filtering %<>% c(UMIs_highUMIbead=sum(df$umi[df$sb_index %in% high_umi_sb]))
df %<>% filter(!sb_index %in% high_umi_sb)
invisible(gc())

message("Plotting bead UMI filtering")
suppressMessages(suppressWarnings(plot_bead_filtering(bead_umi, puckdf, umi_cutoff, out_path, percent_umi_filter)))
rm(bead_umi, high_umi_sb) ; invisible(gc())

# join bead coordinates; puck_boundaries track x-axis offsets for multi-puck layouts
if (!all(df$sb_index %in% puckdf$sb_index)) {
  stop(trouble(
    "some spatial barcodes in the count matrix have no coordinates in the puck table",
    "Every retained read must map to a bead position, or it cannot be placed",
    "This is an internal filtering inconsistency in load_matrix.R rather than a problem with your data",
    "Re-run the spatial analysis from scratch with --spatial-analysis --force",
    "If it persists after a clean re-run, please report it at https://github.com/kabanovskyd/slidr/issues"
  ), call. = FALSE)
}
df %<>% left_join(puckdf, by="sb_index") %>% select(cb_index, x, y, umi) %>% arrange(cb_index, desc(umi))
# count UMIs per puck using the precomputed x-axis boundaries to distinguish adjacent pucks
metadata$puck_info$umi_final = map_int(1:len(metadata$puck_info$puck_name), ~filter(df, x >= metadata$puck_info$puck_boundaries[[.]],
                                                                                    x <= metadata$puck_info$puck_boundaries[[.+1]])$umi %>% sum)

# plot the SBmetrics.pdf summary page with matching and filtering statistics
message("Plotting metadata")
plot_metrics(metadata, out_path)

# write matrix.csv.gz: columns are (cb_index, x_um, y_um, umi), one row per cell-bead pair
# write spatial_metadata.json: all accumulated filtering counts and run parameters
message("Writing results")
df %>% setNames(c("cb_index","x_um","y_um","umi")) %>% write.table(file.path(out_path, "matrix.csv.gz") %>% gzfile, sep=",", col.names=T, row.names=F, quote=F)
metadata %>% map(as.list) %>% toJSON(pretty=T) %>% writeLines(file.path(out_path, "spatial_metadata.json"))
