# input and output paths
paths:
  output_path:
  input_path:
  software_path:
  raw_barcodes_path:
  puck_path:
  reference_path:
  auth_key_path:

# run settings
settings:
  memory: 50
  threads: 16
  metadata_source:
  gcs_download_dest:
  output_bucket:
  reference_genome:
  alerts:
  slack_token:

# workflow components and parameters
workflow:
  generate_bam: false
  cellbender_total_droplets:
  cellbender_estimated_cells:
  cellbender_epochs:
  cellbender_learn_rate:
  spatial_downsampling:
  top_n_percent_umi_filter:
  flex_emptydrops_minimum_umis:
  flex_probe_set:
  flex_spatial_R1_path:
  flex_spatial_R2_path:
  flex_gex_fastqs: